### ISSUE TITLE
Stackoverflow when unroll recursive calls

### ISSUE THREAD

**Issue by ireneGP** [boogie-org/boogie#117]
Hello, 

I am using `Boogie` (as the backend of `Smack`) to perform some model checking tasks. However, currently I am trapped in the following issue:

````
Traceback (most recent call last):
  File "/usr/local/bin/smack", line 13, in <module>
    smack.top.main()
  File "/usr/local/bin/../share/smack/top.py", line 618, in main
    verify_bpl(args)
  File "/usr/local/bin/../share/smack/top.py", line 487, in verify_bpl
    verifier_output = try_command(command, timeout=args.time_limit)
  File "/usr/local/bin/../share/smack/utils.py", line 69, in try_command
    raise Exception(output)
Exception: [ERROR] FATAL UNHANDLED EXCEPTION: System.StackOverflowException: The requested operation caused a stack over
flow.
  at Microsoft.Boogie.LoopUnroll.Visit (Microsoft.Boogie.LoopUnroll+GraphNode node) [0x00007] in <ed84cc86da2b4ac8b8fa07
791cfc2b80>:0
  at Microsoft.Boogie.LoopUnroll.Visit (Microsoft.Boogie.LoopUnroll+GraphNode node) [0x0010e] in <ed84cc86da2b4ac8b8fa07
791cfc2b80>:0

````

Am I supposed to somehow change a threshold or what? Could anyone shed some lights on this? Thanks a lot!

**Comment by shazqadeer** [comment]
I see that loop unrolling controlled by CommandLineOptions.Clo.RecursionBound which is set to 500 by default.  It is likely that you need to supply a smaller bound to SMACK which it will then communicate to Boogie.
