### ISSUE TITLE
Monomorphization: Boogie internal error

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#359]
I get the following exception with the attached bpl source:

```
Unhandled exception. cce+UnreachableException: Exception of type 'cce+UnreachableException' was thrown.
   at Microsoft.Boogie.IdentifierExpr.Typecheck(TypecheckingContext tc) in /home/runner/work/boogie/boogie/Source/Core/AbsyExpr.cs:line 1269
   at Microsoft.Boogie.QKeyValue.Typecheck(TypecheckingContext tc) in /home/runner/work/boogie/boogie/Source/Core/AbsyQuant.cs:line 444
   at Microsoft.Boogie.Cmd.TypecheckAttributes(QKeyValue attributes, TypecheckingContext tc) in /home/runner/work/boogie/boogie/Source/Core/AbsyCmd.cs:line 1664
   at Microsoft.Boogie.AssumeCmd.Typecheck(TypecheckingContext tc) in /home/runner/work/boogie/boogie/Source/Core/AbsyCmd.cs:line 3961
   at Microsoft.Boogie.Block.Typecheck(TypecheckingContext tc) in /home/runner/work/boogie/boogie/Source/Core/AbsyCmd.cs:line 1343
   at Microsoft.Boogie.Implementation.Typecheck(TypecheckingContext tc) in /home/runner/work/boogie/boogie/Source/Core/Absy.cs:line 4509
   at Microsoft.Boogie.Inliner.ProcessImplementation(Program program, Implementation impl, Inliner inliner) in /home/runner/work/boogie/boogie/Source/Core/Inline.cs:line 166
   at Microsoft.Boogie.ExecutionEngine.Inline(Program program) in /home/runner/work/boogie/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 809
   at Microsoft.Boogie.ExecutionEngine.ProcessFiles(IList`1 fileNames, Boolean lookForSnapshots, String programId) in /home/runner/work/boogie/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 510
   at Microsoft.Boogie.OnlyBoogie.Main(String[] args) in /home/runner/work/boogie/boogie/Source/BoogieDriver/BoogieDriver.cs:line 65
Aborted (core dumped)
```

The code in question seems to be this:

```
public override void Typecheck(TypecheckingContext tc)
    {
      //Contract.Requires(tc != null);
      if (this.Decl != null)
      {
        // sanity check
        if (Type != null && !Type.Equals(Decl.TypedIdent.Type))
        {
          tc.Error(this, "internal error, shallow-type assignment was done incorrectly, {0}:{1} != {2}",
            Name, Type, Decl.TypedIdent.Type);
          {
            Contract.Assert(false);
            throw new cce.UnreachableException();
          }
        }

        Type = Decl.TypedIdent.Type;
      }
    }
```
@shazqadeer 

[bug.zip](https://github.com/boogie-org/boogie/files/6200828/bug.zip)

**Comment by wrwg** [comment]
I was able to create a smaller repro. It happens when one tries to print a monomorphized variable:

```
type {:datatype} Cell _;
function {:constructor} Mk<T>(x: T): Cell T;

function {:inline} foo<T>(): Cell T;

procedure p() {
  var x: Cell int;
  x := Mk(1);
  assume {:print "x=", x} true;  // <------- creates the crash
  assert x#Mk(x) == 1;
}

```

**Comment by wrwg** [comment]
After I synced and run the original code which caused this I get a new exception.

```
Process terminated. Assertion failed.
   at Microsoft.Boogie.VCExprAST.VCExprLetBinding..ctor(VCExprVar v, VCExpr e) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/VCExprAST.cs:line 1856
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.VisitLetExpr(LetExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 718
   at Microsoft.Boogie.LetExpr.StdDispatch(StandardVisitor visitor) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyQuant.cs:line 1289
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/StandardVisitor.cs:line 860
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.Translate(Expr expr) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 86
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.TranslateNAryExpr(NAryExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 509
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.VisitNAryExpr(NAryExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 476
   at Microsoft.Boogie.NAryExpr.StdDispatch(StandardVisitor visitor) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyExpr.cs:line 3191
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/StandardVisitor.cs:line 860
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.Translate(Expr expr) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 86
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.VisitLetExpr(LetExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 711
   at Microsoft.Boogie.LetExpr.StdDispatch(StandardVisitor visitor) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyQuant.cs:line 1289
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/StandardVisitor.cs:line 860
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.Translate(Expr expr) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 86
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.TranslateNAryExpr(NAryExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 509
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.VisitNAryExpr(NAryExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 476
   at Microsoft.Boogie.NAryExpr.StdDispatch(StandardVisitor visitor) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyExpr.cs:line 3191
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/StandardVisitor.cs:line 860
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.Translate(Expr expr) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 86
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.TranslateQuantifierExpr(QuantifierExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 603
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.VisitQuantifierExpr(QuantifierExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 560
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.VisitForallExpr(ForallExpr node) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 576
   at Microsoft.Boogie.ForallExpr.StdDispatch(StandardVisitor visitor) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyQuant.cs:line 769
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/StandardVisitor.cs:line 860
   at Microsoft.Boogie.VCExprAST.Boogie2VCExprTranslator.Translate(Expr expr) in /mnt/inv/home/wrwg/gh/boogie/Source/VCExpr/Boogie2VCExpr.cs:line 86
   at Microsoft.Boogie.DeclFreeProverContext.AddAxiom(Axiom ax, String attributes) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/ProverContext.cs:line 240
   at Microsoft.Boogie.Checker.Setup(Program prog, ProverContext ctx) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/Checker.cs:line 249
   at Microsoft.Boogie.Checker..ctor(ConditionGeneration vcgen, Program prog, String logFilePath, Boolean appendLogFile, ProverContext ctx) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/Checker.cs:line 169
   at VC.ConditionGeneration.FindCheckerFor(Boolean isBlocking, Int32 waitTimeinMs, Int32 maxRetries) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/ConditionGeneration.cs:line 576
   at VC.VCGen.SplitAndVerify(Implementation impl, Dictionary`2 gotoCmdOrigins, VerifierCallback callback, ModelViewInfo mvInfo, Outcome& outcome) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/VCGen.cs:line 858
   at VC.VCGen.VerifyImplementation(Implementation impl, VerifierCallback callback) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/VCGen.cs:line 1086
   at VC.ConditionGeneration.VerifyImplementation(Implementation impl, List`1& errors, String requestId) in /mnt/inv/home/wrwg/gh/boogie/Source/VCGeneration/ConditionGeneration.cs:line 137
   at Microsoft.Boogie.ExecutionEngine.VerifyImplementation(Program program, PipelineStatistics stats, ErrorReporterDelegate er, String requestId, Dictionary`2 extractLoopMappingInfo, Implementation[] stablePrioritizedImpls, Int32 index, OutputCollector outputCollector, List`1 checkers, String programId) in /mnt/inv/home/wrwg/gh/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 1201
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass28_2.<InferAndVerify>b__5(Object dummy) in /mnt/inv/home/wrwg/gh/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 992
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.ThreadTaskScheduler.TaskMain(Object data) in /mnt/inv/home/wrwg/gh/boogie/Source/ExecutionEngine/ThreadTaskScheduler.cs:line 50
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Aborted (core dumped)

```

It is happening here:

```
    internal VCExprLetBinding(VCExprVar v, VCExpr e)
    {
      Contract.Requires(e != null);
      Contract.Requires(v != null);
      this.V = v;
      this.E = e;
      Contract.Assert(v.Type.Equals(e.Type));
    }
```

Should I try to construct a new repro? I also attach the zipped full output.bpl; 
[bug.zip](https://github.com/boogie-org/boogie/files/6206728/bug.zip)


Call it with

```
# boogie -doModSetAnalysis -printVerifiedProceduresCount:0 -printModel:1 -enhancedErrorMessages:1 -monomorphize -proverOpt:PROVER_PATH=/home/wrwg/bin/z3 -proverOpt:O:smt.QI.EAGER_THRESHOLD=100 -proverOpt:O:smt.QI.LAZY_THRESHOLD=100 -vcsCores:12 -proverLog:@PROC@.smt output.bpl

```

**Comment by wrwg** [comment]
PS. FYI, commenting the Contract.Assert out lets stuff pass.

**Comment by shazqadeer** [comment]
I will take a look at the repro.
