### ISSUE TITLE
Monomorphization: Assertion failure with recursive function definition

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#363]
Given the following definitions:

```
type {:datatype} Vec _;

function {:constructor} Nil<T>(): Vec T;
function {:constructor} Cons<T>(val: T, nxt: Vec T): Vec T;

function {:inline} RemoveAtVec<T>(v: Vec T, i: int): Vec T {
    if i == 0 then nxt#Cons(v)
    else Cons(val#Cons(v), RemoveAtVec(nxt#Cons(v), i - 1))
}

procedure Test() {
    assert RemoveAtVec(Cons(0, Nil()), 0) == Nil();
}
```

Running this hits an assertion failure:

```
# boogie-dev -monomorphize bug.bpl 
Process terminated. Assertion failed.
   at Microsoft.Boogie.Type.MatchArgumentTypes(List`1 typeParams, List`1 formalArgs, IList`1 actualArgs, List`1 formalOuts, List`1 actualOuts, String opName, TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyType.cs:line 568
   at Microsoft.Boogie.Type.CheckArgumentTypes(List`1 typeParams, List`1& actualTypeParams, List`1 formalIns, IList`1 actualIns, List`1 formalOuts, List`1 actualOuts, IToken typeCheckingSubject, String opName, TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyType.cs:line 650
   at Microsoft.Boogie.FunctionCall.Typecheck(IList`1 actuals, TypeParamInstantiation& tpInstantiation, TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyExpr.cs:line 2695
   at Microsoft.Boogie.NAryExpr.Typecheck(TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyExpr.cs:line 3159
   at Microsoft.Boogie.NAryExpr.Typecheck(TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyExpr.cs:line 3145
   at Microsoft.Boogie.NAryExpr.Typecheck(TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/AbsyExpr.cs:line 3145
   at Microsoft.Boogie.Function.Typecheck(TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/Absy.cs:line 3347
   at Microsoft.Boogie.Program.Typecheck(TypecheckingContext tc) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/Absy.cs:line 478
   at Microsoft.Boogie.Program.Typecheck(IErrorSink errorSink) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/Absy.cs:line 466
   at Microsoft.Boogie.Program.Typecheck() in /mnt/inv/home/wrwg/gh/boogie/Source/Core/Absy.cs:line 460
   at Microsoft.Boogie.ExecutionEngine.ResolveAndTypecheck(Program program, String bplFileName, CivlTypeChecker& civlTypeChecker) in /mnt/inv/home/wrwg/gh/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 729
   at Microsoft.Boogie.ExecutionEngine.ProcessFiles(IList`1 fileNames, Boolean lookForSnapshots, String programId) in /mnt/inv/home/wrwg/gh/boogie/Source/ExecutionEngine/ExecutionEngine.cs:line 479
   at Microsoft.Boogie.OnlyBoogie.Main(String[] args) in /mnt/inv/home/wrwg/gh/boogie/Source/BoogieDriver/BoogieDriver.cs:line 65
```

This is at current main branch.

@shazqadeer

**Comment by wrwg** [comment]
This appears to happen because of the `{:inline}` attribute which was left here accidentally. Because Boogie does not generally disallow to have `{:inline}` at recursive functions, it is still a bug, but the workaround is easy.

**Comment by shazqadeer** [comment]
This [commit](https://github.com/boogie-org/boogie/commit/074a2b7675a06d63a12a9bf808f0b421d7bc9a56) fixes the problem.  Boogie should now report an error message on this example.
