### ISSUE TITLE
Monomorphization: crash with nested type instantiations

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#376]
Given the following Boogie program:

```
type {:datatype} Box _;
type {:datatype} Mut _;

function {:constructor} Box<T>(x: T): Box T;
function {:constructor} Mut<T>(x: T): Mut T;

procedure {:inline} foo(b: Box (Box int)) returns (y: Mut (Box (Box int))) {
   y := Mut(b);
}
```

... Boogie crashes:

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'System.Collections.Generic.List`1[Microsoft.Boogie.Type]' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Boogie.MonomorphizationVisitor.ExprMonomorphizationVisitor.LookupType(Type type) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/Monomorphization.cs:line 414
   at Microsoft.Boogie.MonomorphizationVisitor.ExprMonomorphizationVisitor.<>c__DisplayClass15_0.<VisitNAryExpr>b__1(Type x) in /mnt/inv/home/wrwg/gh/boogie/Source/Core/Monomorphization.cs:line 467
```

@shazqadeer

**Comment by wrwg** [comment]
I debugged this a bit more. Added some console in the VisitTypeCtor method. The output looks as follows:

```
...
type $Mutation(
type Vec(
type Vec()))
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'System.Collections.Generic.List`1[Microsoft.Boogie.Type]' was not present in the dictionary.
```

This prints the ctor, then recursively the visited arguments in `(..)`. It appears that there is a `Vec()` in the input to monomorphization. So not an easy problem to fix at this place.
