### ISSUE TITLE
Boogie crash

### ISSUE THREAD

**Issue by wrwg** [boogie-org/boogie#381]
I'm observing a crash with the attached boogie source:

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: $TestMonomorphization_R'int'
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
...
```

This is with the current head version.

Command line:

```
boogie-dev -doModSetAnalysis -printVerifiedProceduresCount:0 -printModel:1 -enhancedErrorMessages:1 -monomorphize -proverOpt:PROVER_PATH=/home/wrwg/bin/z3 -proverOpt:O:smt.QI.EAGER_THRESHOLD=100 -proverOpt:O:smt.QI.LAZY_THRESHOLD=100 -vcsCores:12 output.bpl
```
[bug.zip](https://github.com/boogie-org/boogie/files/6347579/bug.zip)

@shazqadeer

**Comment by shazqadeer** [comment]
I have put up a PR with a fix.  After the fix, I get the following output:

```
shaz-mbp:Downloads shaz$ myboogie -doModSetAnalysis -printVerifiedProceduresCount:0 -printModel:1 -enhancedErrorMessages:1 -monomorphize -proverOpt:PROVER_PATH=/home/wrwg/bin/z3 -proverOpt:O:smt.QI.EAGER_THRESHOLD=100 -proverOpt:O:smt.QI.LAZY_THRESHOLD=100 -vcsCores:12 output.bpl
output.bpl(1840,18): error: more than one declaration of datatype name: $TestMonomorphization_R'int'
output.bpl(1841,25): error: more than one declaration of datatype constructor name: $TestMonomorphization_R'int'
2 parse errors detected in output.bpl
```

**Comment by wrwg** [comment]
Nice, that's expected. Merging would be great. Thanks for the ultra quick turn around!
